apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runbook-hunter.fullname" . }}-secret
type: Opaque
stringData:
  RH_AUTH_BASIC_USER: {{ .Values.auth.basicUser | quote }}
  RH_AUTH_BASIC_PASS: {{ .Values.auth.basicPass | quote }}
  RH_AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  RH_SETTINGS_CRYPTO_KEY: {{ .Values.secrets.settingsCryptoKey | quote }}
  RH_GITOPS_TOKEN: {{ .Values.secrets.gitopsToken | quote }}
  RH_AWX_TOKEN: {{ .Values.secrets.awxToken | quote }}
